seed: 0
experiment_info:
  params:
    experiment_name: "va_estimation_audio"
    run_name: "audio"
    datetime_format: "%Y-%m-%d_%H-%M"

data:
  name: "audio_va_datamodule"
  params:
    dataset_path: "data/Chunk_wav"
    train_csv: "data/labels_segmented_s2s_wav/train_audio_segment.csv"
    val_csv: "data/labels_segmented_s2s_wav/val_audio_segment.csv"
    test_csv: "data/labels_segmented_s2s_wav/test_audio_segment.csv"
    batch_size: 8
    num_workers: 8
    augment: false
    s2s: true
    s2s_steps: 4
    augment_params:
      aug_noise_prob: 0.6
      aug_snr_db_min: 8.0
      aug_snr_db_max: 25.0
      aug_gain_prob: 0.3
      aug_gain_db_min: -6.0
      aug_gain_db_max: 6.0
      aug_band_prob: 0.3
      aug_reverb_prob: 0.2

model:
  name: "wavlm_s2s_model"
  params:
    model_name: "3loi/SER-Odyssey-Baseline-WavLM-Multi-Attributes"
    freeze_backbone: false
    unfreeze_last_n_layers: 4
    pooling: "attn_stats"       # mean | stats | attn | attn_stats
    head_dropout: 0.2
    input_normalize: true
    attn_hidden_dim: 128
    attn_dropout: 0.2

train:
  params:
    epochs: 50
    mixed_precision: true
    device: "cuda"
    log_every_steps: 50
    grad_clip_norm: 1.0
    use_scheduler: true
    scheduler_step_per_epoch: true
    scheduler_monitor: "val_framewise/va_ccc_metric"

optimizer:
  name: "adamw_two_group_optimizer"
  params:
    lr_backbone: 5.0e-6
    lr_head: 2.0e-4
    weight_decay: 0.01

scheduler:
  name: "named_reduceonplateau_scheduler"
  params:
    mode: "max"
    factor: 0.5
    patience: 2
    threshold: 5.0e-4
    min_lr: 1.0e-7
    cooldown: 0
    target_group_names: ["head"]

loss:
  name: "ccc_mse_loss"
  params:
    ccc_weight: 1
    mse_weight: 0.1
    v_weight: 0.7
    a_weight: 0.3

metrics:
  - name: "va_ccc_metric"
    params: {}

callbacks:
  - name: "audio_framewise_callback"
    params:
      loader_name: "train"
      log_prefix: "train_framewise"
      overlap_strategy: "mean"
      ann_root: "data/labels/VA_Estimation_Challenge"
      ann_split_dir: "Train_Set"
      ann_ext: ".txt"
      dump_pickle: true
      pickle_path: "train.pkl"
      resample_mode: "linear"
  - name: "audio_framewise_callback"
    params:
      loader_name: "val"
      log_prefix: "val_framewise"
      overlap_strategy: "mean"
      ann_root: "data/labels/VA_Estimation_Challenge"
      ann_split_dir: "Validation_Set"
      ann_ext: ".txt"
      dump_pickle: true
      pickle_path: "val.pkl"
      resample_mode: "linear"
  - name: "audio_framewise_callback"
    params:
      loader_name: "test"
      log_prefix: "test_framewise"
      overlap_strategy: "mean"
      ann_root: "data/labels/VA_Estimation_Challenge"
      ann_split_dir: "Test_Set"
      ann_ext: ".txt"
      dump_pickle: true
      pickle_path: "test.pkl"
      resample_mode: "linear"
